## Análise Exploratória de Dados

### Importação de bibliotecas e do conjunto de dados

In [49]:
import pandas as pd

In [50]:
df_pedidos = pd.read_csv("../data/demanda_pedidos_final.csv")
df_produtos = pd.read_csv("../data/demanda_produtos_final.csv")

In [51]:
display(df_pedidos.shape)
df_pedidos.head()

(45807, 3)

      id_produto  quantidade data_pedido
0  1206997678774         2.0  2025-12-31
1  2483458744482         2.0  2025-12-31
2  3115403067986         2.0  2025-12-31
3  4616333531350         2.0  2025-12-31
4  2124623355660         5.0  2025-12-31

In [52]:
display(df_produtos.shape)
df_produtos.head()

(6453, 6)

,id_produto,curva,categoria,fora_de_estoque,indice_de_preco,data_coleta
0,6693862302648,B,Categoria 35,0,0.953917,2026-03-12
1,6693862302648,B,Categoria 35,0,0.953917,2026-03-13
2,6693862302648,B,Categoria 35,0,1.184332,2026-03-14
3,6693862302648,B,Categoria 35,0,1.184332,2026-03-15
4,6693862302648,B,Categoria 35,0,0.953917,2026-03-16

In [53]:
# Ajustando tabela de produtos pra ficar igual à especificação
df_produtos["fora_de_estoque"] = df_produtos["fora_de_estoque"].replace({0: 1, 1: 0})
df_produtos.rename(columns={"fora_de_estoque": "estoque"}, inplace=True)

df_produtos.head()

      id_produto curva     categoria  estoque  indice_de_preco data_coleta
0  6693862302648     B  Categoria 35        1         0.953917  2026-03-12
1  6693862302648     B  Categoria 35        1         0.953917  2026-03-13
2  6693862302648     B  Categoria 35        1         1.184332  2026-03-14
3  6693862302648     B  Categoria 35        1         1.184332  2026-03-15
4  6693862302648     B  Categoria 35        1         0.953917  2026-03-16

In [54]:
df_produtos["data_coleta"].nunique()

91

In [55]:
df_pedidos["data_pedido"].nunique()

92